name: Deploy Web Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Project Dependencies
        with:
          working-directory: ./recipe-voice-app
        run: npm install

      - name: Compile React & Tailwind CSS
        with:
          working-directory: ./recipe-voice-app
        run: npm run build

      - name: Move Files to Nginx Directory
        with:
          working-directory: ./recipe-voice-app
        run: cp -r dist/* /var/www/recipe-app/